/*
Consider all integer combinations of ab for 2 ≤ a ≤ 5 and 2 ≤ b ≤ 5:

22=4, 23=8, 24=16, 25=32
32=9, 33=27, 34=81, 35=243
42=16, 43=64, 44=256, 45=1024
52=25, 53=125, 54=625, 55=3125
If they are then placed in numerical order, with any repeats removed, we get the following sequence of 15 distinct terms:

4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125

How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?
 */

import java.util.HashSet;

public class DistinctPowers {
    public static void main (String[] args ){
    HashSet<Double> numbers = new HashSet<>();

    for(int i=2; i<101;i++){
       for ( int j=2 ; j<101;j++){
            numbers.add(Math.pow(i,j));
       }
    }
        System.out.println(" number of distinct terms : "+ numbers.size()); }
}
